# Generated by Django 4.1.2 on 2022-11-28 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('measurement_unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comorbidity', models.CharField(max_length=50)),
                ('sodium', models.FloatField()),
                ('protein', models.FloatField()),
                ('water', models.FloatField()),
                ('potassium', models.FloatField()),
                ('phosphates', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=7)),
                ('height', models.IntegerField()),
                ('age', models.IntegerField()),
                ('comorbidity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='KHF_app.recommendation')),
            ],
        ),
        migrations.CreateModel(
            name='meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.CharField(max_length=1000)),
                ('meal_type', models.PositiveSmallIntegerField(choices=[(1, 'Breakfast'), (2, 'Lunch'), (3, 'Dinner'), (4, 'Snack'), (5, 'Water')], default=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='KHF_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='food_item_in_meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('food_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KHF_app.food_item')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KHF_app.meal')),
            ],
        ),
        migrations.AddField(
            model_name='food_item',
            name='meals',
            field=models.ManyToManyField(blank=True, through='KHF_app.food_item_in_meal', to='KHF_app.meal'),
        ),
    ]
