# Generated by Django 4.1.2 on 2022-11-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHF_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
