# Generated by Django 4.1.2 on 2022-11-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHF_app', '0003_alter_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='cole0hardy@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
